name: Optimism Worldchain Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - production-optimism-worldchain
permissions:
  contents: read
  packages: write

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: 9.3.2
      DOCKER_CHAIN_NAME: optimism
    steps:
      - uses: actions/checkout@v5
      - name: Setup repo
        uses: ./.github/actions/setup-repo
        id: setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (indexer + API)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/valeamoris/blockscout-${{ env.DOCKER_CHAIN_NAME }}-private:${{ env.RELEASE_VERSION }}-postrelease-${{ env.SHORT_SHA }}-worldchain
          labels: ${{ steps.setup.outputs.docker-labels }}
          platforms: |
            linux/amd64
          build-args: |
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}.+commit.${{ env.SHORT_SHA }}
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            CHAIN_TYPE=optimism

      - name: Build and push Docker image (indexer)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/valeamoris/blockscout-${{ env.DOCKER_CHAIN_NAME }}-private:${{ env.RELEASE_VERSION }}-postrelease-${{ env.SHORT_SHA }}-worldchain-indexer
          labels: ${{ steps.setup.outputs.docker-labels }}
          platforms: |
            linux/amd64
          build-args: |
            DISABLE_API=true
            BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}.+commit.${{ env.SHORT_SHA }}
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            CHAIN_TYPE=optimism
